services:
  - type: web
    name: ethio-tech-api
    env: node
    region: ohio
    buildCommand: npm run build -w backend
    startCommand: npm start -w backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        sync: false
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: LIVE_CLASSROOM_SECRET
        sync: false

  - type: static
    name: ethio-tech-frontend
    env: static
    region: ohio
    buildCommand: npm run build -w frontend
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
