import { Router } from "express";

import authRoutes from "./authRoutes.js";
import userRoutes from "./userRoutes.js";
import trackRoutes from "./trackRoutes.js";
import moduleRoutes from "./moduleRoutes.js";
import lessonRoutes from "./lessonRoutes.js";
import projectRoutes from "./projectRoutes.js";
import submissionRoutes from "./submissionRoutes.js";
import xpRoutes from "./xpRoutes.js";
import sessionRoutes from "./sessionRoutes.js";
import peerGroupRoutes from "./peerGroupRoutes.js";
import leaderboardRoutes from "./leaderboardRoutes.js";
import marketingRoutes from "./marketingRoutes.js";
import mentorApplicationRoutes from "./mentorApplicationRoutes.js";
import resourceRoutes from "./resourceRoutes.js";
import notificationRoutes from "./notificationRoutes.js";
import notificationPreferenceRoutes from "./notificationPreferenceRoutes.js";
import hubRoutes from "./hubRoutes.js";
import dashboardRoutes from "./dashboardRoutes.js";
import badgeRoutes from "./badgeRoutes.js";
import certificateRoutes from "./certificateRoutes.js";
import adminRoutes from "./adminRoutes.js";
import gamificationRoutes from "./gamificationRoutes.js";
import contactRoutes from "./contactRoutes.js";
import chatRoutes from "./chatRoutes.js";
import parentRoutes from "./parentRoutes.js";
import mentorAvailabilityRoutes from "./mentorAvailabilityRoutes.js";
import analyticsRoutes from "./analyticsRoutes.js";
import analyticsEventRoutes from "./analyticsEventRoutes.js";
import sessionQuestionRoutes from "./sessionQuestionRoutes.js";
import sessionPollRoutes from "./sessionPollRoutes.js";
import sessionEngagementRoutes from "./sessionEngagementRoutes.js";
import sessionNoteRoutes from "./sessionNoteRoutes.js";
import sessionResourceRoutes from "./sessionResourceRoutes.js";
import sessionModerationRoutes from "./sessionModerationRoutes.js";
import sessionRecordingRoutes from "./sessionRecordingRoutes.js";
import handRaiseRoutes from "./handRaiseRoutes.js";
import mentorStudentFeedbackRoutes from "./mentorStudentFeedbackRoutes.js";
import mentorAnalyticsRoutes from "./mentorAnalyticsRoutes.js";
import agoraRoutes from "./agoraRoutes.js";
import whiteboardRoutes from "./whiteboardRoutes.js";
import breakoutRoutes from "./breakoutRoutes.js";
import dmRoutes from "./dmRoutes.js";
import cohortRoutes from "./cohortRoutes.js";
import assignmentRoutes from "./assignmentRoutes.js";
import calendarRoutes from "./calendarRoutes.js";
import recommendationRoutes from "./recommendationRoutes.js";
import { globalRateLimit } from "../services/rateLimitService.js";

const router = Router();

router.use(globalRateLimit);

router.use("/auth", authRoutes);
router.use("/users", userRoutes);
router.use("/tracks", trackRoutes);
router.use("/modules", moduleRoutes);
router.use("/lessons", lessonRoutes);
router.use("/projects", projectRoutes);
router.use("/submissions", submissionRoutes);
router.use("/xp", xpRoutes);
router.use("/sessions", sessionRoutes);
router.use("/sessions/:sessionId/questions", sessionQuestionRoutes);
router.use("/sessions/:sessionId/polls", sessionPollRoutes);
router.use("/sessions/:sessionId/engagement", sessionEngagementRoutes);
router.use("/sessions/:sessionId/notes", sessionNoteRoutes);
router.use("/sessions/:sessionId/resources", sessionResourceRoutes);
router.use("/sessions/:sessionId/moderation", sessionModerationRoutes);
router.use("/sessions/:sessionId/recordings", sessionRecordingRoutes);
router.use("/sessions/:sessionId/hands", handRaiseRoutes);
router.use("/sessions/:sessionId/student-feedback", mentorStudentFeedbackRoutes);
router.use("/mentor", mentorAnalyticsRoutes);
router.use("/peer-groups", peerGroupRoutes);
router.use("/leaderboard", leaderboardRoutes);
router.use("/marketing", marketingRoutes);
router.use("/mentor-applications", mentorApplicationRoutes);
router.use("/resources", resourceRoutes);
router.use("/notifications", notificationRoutes);
router.use("/notification-preferences", notificationPreferenceRoutes);
router.use("/hubs", hubRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/badges", badgeRoutes);
router.use("/certificates", certificateRoutes);
router.use("/admin", adminRoutes);
router.use("/gamification", gamificationRoutes);
router.use("/contact", contactRoutes);
router.use("/chat", chatRoutes);
router.use("/parent", parentRoutes);
router.use("/mentor-availability", mentorAvailabilityRoutes);
router.use("/analytics", analyticsRoutes);
router.use("/analytics/events", analyticsEventRoutes);
router.use("/sessions", agoraRoutes);
router.use("/sessions/:sessionId", whiteboardRoutes);
router.use("/sessions", breakoutRoutes);
router.use("/dm", dmRoutes);
router.use("/cohorts", cohortRoutes);
router.use("/assignments", assignmentRoutes);
router.use("/calendar", calendarRoutes);
router.use("/recommendations", recommendationRoutes);

export default router;
