export const ROLES = {
  SUPER_ADMIN: "super_admin",
  ADMIN: "admin",
  MODERATOR: "moderator",
  REVIEWER: "reviewer",
  SUPPORT: "support",
  MENTOR: "mentor",
  STUDENT: "student",
};

export const ROLE_HIERARCHY = {
  super_admin: 100,
  admin: 80,
  moderator: 60,
  reviewer: 50,
  support: 40,
  mentor: 30,
  student: 10,
};

export const PERMISSIONS = {
  USER_CREATE: "user.create",
  USER_EDIT: "user.edit",
  USER_DELETE: "user.delete",
  USER_SOFT_DELETE: "user.soft_delete",
  USER_RESTORE: "user.restore",
  USER_SUSPEND: "user.suspend",
  USER_BAN: "user.ban",
  USER_REACTIVATE: "user.reactivate",
  USER_VERIFY: "user.verify",
  USER_RESET_PASSWORD: "user.reset_password",
  USER_FORCE_LOGOUT: "user.force_logout",
  USER_CHANGE_ROLE: "user.change_role",
  USER_EXPORT: "user.export",
  USER_VIEW_SENSITIVE: "user.view_sensitive",
  MENTOR_APPROVE: "mentor.approve",
  MENTOR_REJECT: "mentor.reject",
  MENTOR_REQUEST_CHANGES: "mentor.request_changes",
  MENTOR_VIEW_APPLICATIONS: "mentor.view_applications",
  MENTOR_PROVISION: "mentor.provision",
  MENTOR_RESEND_CREDENTIALS: "mentor.resend_credentials",
  MENTOR_SUSPEND: "mentor.suspend",
  MENTOR_ARCHIVE: "mentor.archive",
  SESSION_MANAGE: "session.manage",
  SESSION_MODERATE: "session.moderate",
  SESSION_QUESTION_MANAGE: "session.question.manage",
  SESSION_POLL_MANAGE: "session.poll.manage",
  SESSION_PARTICIPANT_CONTROL: "session.participant.control",
  SESSION_MODERATION: "session.moderation",
  SESSION_RESOURCE_SHARE: "session.resource.share",
  SESSION_RECORDING_MANAGE: "session.recording.manage",
  SESSION_NOTE_MANAGE: "session.note.manage",
  SESSION_ENGAGEMENT_VIEW: "session.engagement.view",
  ANALYTICS_VIEW: "analytics.view",
  ANALYTICS_EXPORT: "analytics.export",
  AUDIT_VIEW: "audit.view",
  AUDIT_EXPORT: "audit.export",
  CONTENT_MANAGE: "content.manage",
  GAMIFICATION_MANAGE: "gamification.manage",
  BULK_ACTIONS: "bulk.actions",
  ANNOUNCEMENT_SEND: "announcement.send",
  SETTINGS_MANAGE: "settings.manage",
};

export const ROLE_PERMISSIONS = {
  super_admin: Object.values(PERMISSIONS),
  admin: [
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_EDIT,
    PERMISSIONS.USER_DELETE,
    PERMISSIONS.USER_SOFT_DELETE,
    PERMISSIONS.USER_RESTORE,
    PERMISSIONS.USER_SUSPEND,
    PERMISSIONS.USER_BAN,
    PERMISSIONS.USER_REACTIVATE,
    PERMISSIONS.USER_VERIFY,
    PERMISSIONS.USER_RESET_PASSWORD,
    PERMISSIONS.USER_FORCE_LOGOUT,
    PERMISSIONS.USER_CHANGE_ROLE,
    PERMISSIONS.USER_EXPORT,
    PERMISSIONS.USER_VIEW_SENSITIVE,
    PERMISSIONS.MENTOR_APPROVE,
    PERMISSIONS.MENTOR_REJECT,
    PERMISSIONS.MENTOR_REQUEST_CHANGES,
    PERMISSIONS.MENTOR_VIEW_APPLICATIONS,
    PERMISSIONS.MENTOR_PROVISION,
    PERMISSIONS.MENTOR_RESEND_CREDENTIALS,
    PERMISSIONS.MENTOR_SUSPEND,
    PERMISSIONS.MENTOR_ARCHIVE,
    PERMISSIONS.SESSION_MANAGE,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.ANALYTICS_EXPORT,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.AUDIT_EXPORT,
    PERMISSIONS.CONTENT_MANAGE,
    PERMISSIONS.GAMIFICATION_MANAGE,
    PERMISSIONS.BULK_ACTIONS,
    PERMISSIONS.ANNOUNCEMENT_SEND,
    PERMISSIONS.SETTINGS_MANAGE,
  ],
  moderator: [
    PERMISSIONS.USER_EDIT,
    PERMISSIONS.USER_SUSPEND,
    PERMISSIONS.USER_REACTIVATE,
    PERMISSIONS.USER_VIEW_SENSITIVE,
    PERMISSIONS.MENTOR_VIEW_APPLICATIONS,
    PERMISSIONS.SESSION_MODERATE,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.CONTENT_MANAGE,
  ],
  reviewer: [
    PERMISSIONS.USER_VIEW_SENSITIVE,
    PERMISSIONS.MENTOR_VIEW_APPLICATIONS,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.CONTENT_MANAGE,
  ],
  support: [
    PERMISSIONS.USER_EDIT,
    PERMISSIONS.USER_VIEW_SENSITIVE,
    PERMISSIONS.USER_RESET_PASSWORD,
  ],
  mentor: [
    PERMISSIONS.SESSION_MANAGE,
    PERMISSIONS.SESSION_QUESTION_MANAGE,
    PERMISSIONS.SESSION_POLL_MANAGE,
    PERMISSIONS.SESSION_PARTICIPANT_CONTROL,
    PERMISSIONS.SESSION_MODERATION,
    PERMISSIONS.SESSION_RESOURCE_SHARE,
    PERMISSIONS.SESSION_RECORDING_MANAGE,
    PERMISSIONS.SESSION_NOTE_MANAGE,
    PERMISSIONS.SESSION_ENGAGEMENT_VIEW,
    PERMISSIONS.ANALYTICS_VIEW,
  ],
  student: [],
};

export const USER_STATUS = {
  PENDING: "pending",
  ACTIVE: "active",
  INACTIVE: "inactive",
  SUSPENDED: "suspended",
  BANNED: "banned",
  REJECTED: "rejected",
  DELETED: "deleted",
};

export const VALID_STATUS_TRANSITIONS = {
  [USER_STATUS.PENDING]: [USER_STATUS.ACTIVE, USER_STATUS.INACTIVE, USER_STATUS.REJECTED],
  [USER_STATUS.ACTIVE]: [USER_STATUS.INACTIVE, USER_STATUS.SUSPENDED, USER_STATUS.BANNED, USER_STATUS.DELETED],
  [USER_STATUS.INACTIVE]: [USER_STATUS.ACTIVE, USER_STATUS.SUSPENDED, USER_STATUS.BANNED, USER_STATUS.DELETED],
  [USER_STATUS.SUSPENDED]: [USER_STATUS.ACTIVE, USER_STATUS.BANNED, USER_STATUS.DELETED],
  [USER_STATUS.BANNED]: [USER_STATUS.DELETED],
  [USER_STATUS.REJECTED]: [USER_STATUS.PENDING, USER_STATUS.DELETED],
  [USER_STATUS.DELETED]: [],
};

export const MENTOR_STATUS = {
  PENDING: "pending",
  APPROVED: "approved",
  REJECTED: "rejected",
  CHANGES_REQUESTED: "changes_requested",
  ARCHIVED: "archived",
};

export const APPLICATION_STATUS = {
  PENDING_REVIEW: "pending_review",
  APPROVED: "approved",
  REJECTED: "rejected",
  CHANGES_REQUESTED: "changes_requested",
  ARCHIVED: "archived",
};

export const MENTOR_ACCOUNT_STATUS = {
  PENDING: "pending",
  INVITED: "invited",
  FIRST_LOGIN_PENDING: "first_login_pending",
  PASSWORD_RESET_REQUIRED: "password_reset_required",
  ACTIVATED: "activated",
  ACTIVE: "active",
  SUSPENDED: "suspended",
  DISABLED: "disabled",
  ARCHIVED: "archived",
  REJECTED: "rejected",
};

export const VALID_MENTOR_ACCOUNT_TRANSITIONS = {
  [MENTOR_ACCOUNT_STATUS.PENDING]: [
    MENTOR_ACCOUNT_STATUS.INVITED,
    MENTOR_ACCOUNT_STATUS.REJECTED,
    MENTOR_ACCOUNT_STATUS.ARCHIVED,
  ],
  [MENTOR_ACCOUNT_STATUS.INVITED]: [
    MENTOR_ACCOUNT_STATUS.FIRST_LOGIN_PENDING,
    MENTOR_ACCOUNT_STATUS.PASSWORD_RESET_REQUIRED,
    MENTOR_ACCOUNT_STATUS.ACTIVATED,
    MENTOR_ACCOUNT_STATUS.SUSPENDED,
    MENTOR_ACCOUNT_STATUS.DISABLED,
    MENTOR_ACCOUNT_STATUS.ARCHIVED,
  ],
  [MENTOR_ACCOUNT_STATUS.FIRST_LOGIN_PENDING]: [
    MENTOR_ACCOUNT_STATUS.ACTIVATED,
    MENTOR_ACCOUNT_STATUS.PASSWORD_RESET_REQUIRED,
    MENTOR_ACCOUNT_STATUS.SUSPENDED,
  ],
  [MENTOR_ACCOUNT_STATUS.PASSWORD_RESET_REQUIRED]: [
    MENTOR_ACCOUNT_STATUS.ACTIVATED,
    MENTOR_ACCOUNT_STATUS.FIRST_LOGIN_PENDING,
    MENTOR_ACCOUNT_STATUS.SUSPENDED,
  ],
  [MENTOR_ACCOUNT_STATUS.ACTIVATED]: [
    MENTOR_ACCOUNT_STATUS.ACTIVE,
    MENTOR_ACCOUNT_STATUS.SUSPENDED,
    MENTOR_ACCOUNT_STATUS.DISABLED,
  ],
  [MENTOR_ACCOUNT_STATUS.ACTIVE]: [
    MENTOR_ACCOUNT_STATUS.SUSPENDED,
    MENTOR_ACCOUNT_STATUS.DISABLED,
    MENTOR_ACCOUNT_STATUS.ARCHIVED,
  ],
  [MENTOR_ACCOUNT_STATUS.SUSPENDED]: [
    MENTOR_ACCOUNT_STATUS.ACTIVE,
    MENTOR_ACCOUNT_STATUS.DISABLED,
    MENTOR_ACCOUNT_STATUS.ARCHIVED,
  ],
  [MENTOR_ACCOUNT_STATUS.DISABLED]: [
    MENTOR_ACCOUNT_STATUS.ACTIVE,
    MENTOR_ACCOUNT_STATUS.ARCHIVED,
  ],
  [MENTOR_ACCOUNT_STATUS.ARCHIVED]: [],
  [MENTOR_ACCOUNT_STATUS.REJECTED]: [MENTOR_ACCOUNT_STATUS.ARCHIVED],
};

export const CREDENTIALS_DELIVERY_METHOD = {
  EMAIL: "email",
  ACTIVATION_LINK: "activation_link",
  MANUAL: "manual",
};

export const RATE_LIMITS = {
  ADMIN_USER_CREATE: { windowMs: 60 * 1000, max: 10 },
  ADMIN_USER_DELETE: { windowMs: 60 * 1000, max: 5 },
  ADMIN_USER_SUSPEND: { windowMs: 60 * 1000, max: 20 },
  ADMIN_USER_ACTION: { windowMs: 60 * 1000, max: 30 },
  ADMIN_BULK_ACTION: { windowMs: 60 * 1000, max: 3 },
  ADMIN_EXPORT: { windowMs: 5 * 60 * 1000, max: 5 },
};

export const DELETION_RETENTION_DAYS = 30;
